### ISSUE TITLE
可以修改弹幕样式吗

### ISSUE THREAD

**Issue by SakuraMio2006** [Tony15246/uosc_danmaku#1]
修改字体大小，透明度，速度等等

**Comment by Tony15246** [comment]
可以修改，因为弹幕转换功能是通过调用[DanmakuFactory](https://github.com/hihkm/DanmakuFactory)的二进制文件进行的。只要在调用DanmakuFactory的命令中，添加需要的选项就可以自定义弹幕样式

https://github.com/Tony15246/uosc_danmaku/blob/885bec01892dfebb25f28ef6b203fef570efbe96/api.lua#L512-L519

以上是我源代码中调用DanmakuFactory的命令，没有指定任何设置，全部按照DanmakuFactory的默认配置生成

假如说你希望字体大小为40，滚动弹幕通过屏幕的时间为12秒，字体透明度为70，那就可以把上面展示的源码的部分修改为以下的样子

``` lua
local cmd = {
    danmaku_factory_path,
    "-o",
    danmaku_path .. "danmaku.ass",
    "-i",
    danmaku_path .. "danmaku.json",
    "--fontsize",
    "40",
    "--scrolltime",
    "12",
    "--opacity",
    "70",
    "--ignore-warnings",
}
```
其他可设置选项可以参考DanmakuFactory的help手册，固定弹幕停留时间、弹幕字体、弹幕密度等均可自定义

> DanmakuFactory 1.70 CLI Release by hkm (hkm@tikm.org)
> https://github.com/hihkm/DanmakuFactory
> 
> Usage:
> DanmakuFactory -o [outfile_format] outfile -i [infile1_template] infile1 [infile2_template] infile2 ... [-t infile1_timeshift ...] [configuration value] ...
> 
> Format:
> xml, json, ass
> 
> Template:
> xml, json, ass or a template name
> 
> Configurations:
> -r, --resolution    Specify the value of resolution.
>                     Use any character to connect width and height, like "1920x1080".
> -s, --scrolltime    Specify the time of rolling danmaku to across the screen.
> -f, --fixtime       Specify the time of fix danmaku show on the screen.
> -d, --density       Specify the maximum number of danmaku could show on the screen at the same time.
>                     Special value: -1 non-overlap, 0 unlimit
> 
> -S, --fontsize      Specify the fontsize of general danmaku.
> -N, --fontname      Specify the fontname of general danmaku.
> -O, --opacity       Specify the opacity of danmaku EXCEPT the special danmaku(range: 1-255).
> -L, --outline       Specify the width of outline for each danmaku(range: 0-4).
> -D, --shadow        Specify the depth of shadow for each danmaku(range: 0-4).
> -B, --bold          Specify whether the font should be boldface.
>                     Available value: TRUE, FALSE
> 
> --displayarea       Specify the percent of display area on the screen(range: 0.0-1.0).
> --scrollarea        Specify the percent of scroll area of rolling danmaku on the screen(range: 0.0-1.0).
> 
> -b, --blockmode     Specify the type of danmaku which will not show on the screen.
>                     Use '-' to connect the type-name, like "L2R-TOP-BOTTOM".
>                     Available value: L2R, R2L, TOP, BOTTOM, SPECIAL, COLOR, REPEAT
> 
> --statmode          Specify the type of statistic box which will show on the screen.
>                     Use '-' to connect the type-name, like "TABLE-HISTOGRAM".
>                     Available value: TABLE, HISTOGRAM
> 
> --showusernames     Specify whether show usernames or not.
>                     Available value: TRUE, FALSE
> --showmsgbox        Specify whether show message box or not.
>                     Available value: TRUE, FALSE
> --msgboxsize        Specify the size of message box.
>                     Use any character to connect width and height, like "400x1000".
> --msgboxpos         Specify the position of message box.
>                     Use any character to connect posX and posY, like "50x50".
> --msgboxfontsize    Specify the fontsize of message box.
> --msgboxduration    Specify the duration of message box.
>                     If set, will overwrite default value read from xml.
> --giftminprice      Specify the the minimum price of the gifts, like "5.20" Yuan.
> 
> Other options:
> -h, --help          Display this help and version information than exit.
> -c, --config        Display configuration information and exit.
> --save              Save configuration as current command settings.
> --ignore-warnings   Ignore all warnings, like `-y, --yes`.
> 
> Example:
> DanmakuFactory -o ass "outfile.ass" -i xml "infile1.xml"
> DanmakuFactory -o "outfile.ass" -i "infile1.xml"
> DanmakuFactory -o "outfile.ass" -i "infile1.xml" "infile2.json" "infile3.ass" -t 0.0 5.0 7.0

**Comment by Tony15246** [comment]
按道理来说，其实现自定义设置不应该让用户直接修改源码。因为我的插件目前基本是我个人自用，作为开发者可以说没有面向的用户，所以没有做对自定义弹幕设置进行封装和对用户隐藏的逻辑。如果你嫌修改源码太麻烦，我也可以把自定义设置封装到`script-opts`文件下的`uosc_danmaku.conf`文件里，这样就可以直接在`uosc_danmaku.conf`里指定弹幕样式设置，不用自己修改源码了。当然，如果你自己就是程序员，或者有开发经验，不反感按照上面描述的内容手动修改源码的话，我就不封装弹幕自定义设置了。毕竟我的插件现在也没多少用户，花费精力在用户友好性上的意义不是很大。

**Comment by SakuraMio2006** [comment]
感谢

**Comment by Tony15246** [comment]
> 感谢

不用谢，我有空闲的话会考虑把弹幕自定义设置封装到script-opts文件下的uosc_danmaku.conf文件中。不过最近比较忙，也可能就不了了之了。

**Comment by Tony15246** [comment]
在此次pull request中完成弹幕自定义设置封装到script-opts文件下的uosc_danmaku.conf文件中 #7
