### ISSUE TITLE
弹幕屏蔽能支持一下正则表达式吗

### ISSUE THREAD

**Issue by wan0ge** [Tony15246/uosc_danmaku#13]

**Comment by Tony15246** [comment]
目前本插件对于使用black.txt进行弹幕屏蔽词指定的功能是依赖第三方项目DanmakuFactory进行实现的，这方面的新需求可以去DanmakuFactory项目提issue询问

https://github.com/hihkm/DanmakuFactory/issues

**Comment by MiKoto-Railgun** [comment]
> 目前本插件对于使用black.txt进行弹幕屏蔽词指定的功能是依赖第三方项目DanmakuFactory进行实现的，这方面的新需求可以去DanmakuFactory项目提issue询问
> 
> https://github.com/hihkm/DanmakuFactory/issues

![image](https://github.com/user-attachments/assets/a8a6b7f9-8913-46f9-aeb8-30100106e0d7)

话说能否在这里直接添加text的正则表达式判断，如果符合就屏蔽渲染这一行弹幕，这样应该不影响渲染吧

**Comment by dyphire** [comment]
> > 目前本插件对于使用black.txt进行弹幕屏蔽词指定的功能是依赖第三方项目DanmakuFactory进行实现的，这方面的新需求可以去DanmakuFactory项目提issue询问
> > https://github.com/hihkm/DanmakuFactory/issues
> 
> ![image](https://private-user-images.githubusercontent.com/191962337/399245891-a8a6b7f9-8913-46f9-aeb8-30100106e0d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU3MjQzMDYsIm5iZiI6MTczNTcyNDAwNiwicGF0aCI6Ii8xOTE5NjIzMzcvMzk5MjQ1ODkxLWE4YTZiN2Y5LTg5MTMtNDZmOS1hZWI4LTMwMTAwMTA2ZTBkNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwMVQwOTMzMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NTFkNWM2ZWY2ZTYwZWY3YjVlNTZkNDk5NjRlOTYxMDJiMzkyYTVkZjM4YTk3M2FjMTRmM2U2OTUxZDk3ZGQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tOxzHDb0dHYkcy4vrJx11qPbq6D5lHDlaOsXzgBIShI)
> 
> 话说能否在这里直接添加text的正则表达式判断，如果符合就屏蔽跳过渲染这一行弹幕，这样应该不影响渲染吧
> 
> 我看了一下之前的版本，当时不是用的overly渲染，现在应该可以了，这样应该就可以实现正则表达式屏蔽弹幕了

一个是 lua 的正则是伪正则，语法也有很大的不同，弹幕屏蔽的正则都以弹弹和 b 站为基准，没有可复用性也就没有实现的必要。另一个是在 render 中实时进行正则过滤在此前的基准性能测试中影响很大，没有实现的价值

**Comment by MiKoto-Railgun** [comment]
> 一个是 lua 的正则是伪正则，语法也有很大的不同，弹幕屏蔽的正则都以弹弹和 b 站为基准，没有可复用性也就没有实现的必要。

嗯，的确，昨天我准备实现才发现这个问题，今天就一直在搞将正则表达式试着替换成lua伪正则，无奈实现过程过于烦琐且难度极大，只好被迫放弃。

>另一个是在 render 中实时进行正则过滤在此前的基准性能测试中影响很大，没有实现的价值

这个还不知道影响这么大，看来放弃对了

**Comment by Tony15246** [comment]
> > 一个是 lua 的正则是伪正则，语法也有很大的不同，弹幕屏蔽的正则都以弹弹和 b 站为基准，没有可复用性也就没有实现的必要。
> 
> 嗯，的确，昨天我准备实现才发现这个问题，今天就一直在搞将正则表达式试着替换成lua伪正则，无奈实现过程过于烦琐且难度极大，只好被迫放弃。
> 
> > 另一个是在 render 中实时进行正则过滤在此前的基准性能测试中影响很大，没有实现的价值
> 
> 这个还不知道影响这么大，看来放弃对了

hhh，要严格意义上正确处理正则表达式，就要实现从一般正则表达式到lua伪正则作为目标代码的翻译，相当于手搓一个小编译器，这个难度和工作量还是有点大的

想到这个就想到当初被编译原理专业课支配的恐怖日子😭

**Comment by wan0ge** [comment]
上游支持了诶！
https://github.com/hihkm/DanmakuFactory/pull/118

**Comment by dyphire** [comment]
嗯，虽然 DanmukuFactory 支持了正则很不错，但我已经计划废弃对 DanmukuFactory 的依赖了，后面打算把解析和转换完全放到 lua 脚本中实现。已经初步实现了（

**Comment by dyphire** [comment]
> 嗯，虽然 DanmukuFactory 支持了正则很不错，但我已经计划废弃对 DanmukuFactory 的依赖了，后面打算把解析和转换完全放到 lua 脚本中实现。已经初步实现了（

见 https://github.com/Tony15246/uosc_danmaku/pull/244
新的内部实现也已支持黑名单正则匹配（需使用 lua 正则写法
