### ISSUE TITLE
[求助]配置插件后不起效

### ISSUE THREAD

**Issue by thouser8** [Tony15246/uosc_danmaku#15]
按照教程操作后正常配置好了控件和快捷键，将bin文件夹设为可执行权限，但是使用中无法生效（按了没反应）。求助是哪里没有正确配置，感谢。
使用的mpv版本为https://github.com/dyphire/mpv-config/releases/tag/mpv_config-2024.09.14
![image](https://github.com/user-attachments/assets/9cd1e4ec-5c40-4b3f-b3ab-402b82d8eafa)

**Comment by Tony15246** [comment]
可以在命令行中运行mpv，把mpv的输出记录下来吗？我看一下是否有什么报错

**Comment by thouser8** [comment]
> 可以在命令行中运行mpv，把mpv的输出记录下来吗？我看一下是否有什么报错

抱歉，我不知道如何记录输出，可以请你简单说明一下吗

**Comment by Tony15246** [comment]
> 抱歉，我不知道如何记录输出，可以请你简单说明一下吗

你是使用的windows系统还是linux系统？linux系统的话用下面这个命令就行

```
mpv xxx.mp4
```

如果是windows系统的话会稍微麻烦一点，输出不会直接显示在命令行里。你需要在mpv.conf里配置log-file配置项比如说配置成

```
log-file=~~mpv.log
```

这样就行。mpv的运行日志会被记录在mpv的根目录下，和mpv.exe在一个地方。如果log-file配置项已经被配置过了，那mpv的根目录下应该就有日志文件。把这个文件删掉或者清除掉其中的所有记录，重新用mpv播放视频后使用插件，让mpv记录一次新日志，然后把运行日志的文件贴到comment里就行。

**Comment by thouser8** [comment]
> > 抱歉，我不知道如何记录输出，可以请你简单说明一下吗
> 
> 你是使用的windows系统还是linux系统？linux系统的话用下面这个命令就行
> 
> ```
> mpv xxx.mp4
> ```
> 
> 如果是windows系统的话会稍微麻烦一点，输出不会直接显示在命令行里。你需要在mpv.conf里配置log-file配置项比如说配置成
> 
> ```
> log-file=~~mpv.log
> ```
> 
> 这样就行。mpv的运行日志会被记录在mpv的根目录下，和mpv.exe在一个地方。如果log-file配置项已经被配置过了，那mpv的根目录下应该就有日志文件。把这个文件删掉或者清除掉其中的所有记录，重新用mpv播放视频后使用插件，让mpv记录一次新日志，然后把运行日志的文件贴到comment里就行。

是windows，我看了一下发现已经配置过了，但是在根目录中没有看到日志文件
![image](https://github.com/user-attachments/assets/742ef0bb-33a9-4e6e-a780-4a39f9f6308e)

**Comment by Tony15246** [comment]
也可能是在portable_config文件夹下，你看一眼呢

**Comment by thouser8** [comment]
> 也可能是在portable_config文件夹下，你看一眼呢

抱歉，刚才应该是我没有在mpv.conf中启用log-file配置项。
[mpv.log](https://github.com/user-attachments/files/17360207/mpv.log)

**Comment by Tony15246** [comment]
没事儿，我看看日志哈

**Comment by Tony15246** [comment]
你尝试一下把api.lua的253行改成
```
path = utils.join_path(directory, path:gusb('^%.[\\/]',''))
```
这样以后再试一下。尝试之前记得删除或者清理一下mpv.log，如果问题还存在的话，把新的mpv.log发给我看一下

**Comment by thouser8** [comment]
> 你尝试一下把api.lua的253行改成
> 
> ```
> path = utils.join_path(directory, path:gusb('^%.[\\/]',''))
> ```
> 
> 这样以后再试一下。尝试之前记得删除或者清理一下mpv.log，如果问题还存在的话，把新的mpv.log发给我看一下

还是没反应，[mpv.log](https://github.com/user-attachments/files/17360358/mpv.log)

**Comment by Tony15246** [comment]
方法名写错了这么低级的错误，我之前怎么都没发现😂
把api.lua的253行改成

```
path = utils.join_path(directory, path:gsub('^%.[\\/]',''))
```
再尝试一下看看

**Comment by Tony15246** [comment]
哎呀，不好意思！我说错了

不是改第253行，是第230行

**Comment by thouser8** [comment]
> 哎呀，不好意思！我说错了
> 
> 不是改第253行，是第230行
> 
> 就是把原本长成下面这样的那一行
> 
> ```
>             path = mp.utils.join_path(directory, path:gusb('^%.[\\/]',''))
> ```
> 
> 改成这样子
> 
> ```
>             path = utils.join_path(directory, path:gsub('^%.[\\/]',''))
> ```

ok这下确实可以了，非常感谢您的帮助🙏

**Comment by Tony15246** [comment]
不用谢，感谢你帮我测试了一个我的本地环境下无法出现的bug👍我回头会推一个fix到主分支。

**Comment by thouser8** [comment]
> 不用谢，感谢你帮我测试了一个我的本地环境下无法出现的bug👍我回头会推一个fix到主分支。

我试了一下，发现本项目和这个项目https://github.com/Kosette/danmaku 是可以兼容的👍但是本项目还不支持emby网络播放对吗

**Comment by Tony15246** [comment]
> 我试了一下，发现本项目和这个项目https://github.com/Kosette/danmaku 是可以兼容的👍但是本项目还不支持emby网络播放对吗

是支持emby网络播放的。只要能调用mpv，并且可以使用自己的自定义配置就能够使用本插件。但是在emby在线播放的时候不支持使用全自动弹幕加载和记忆功能，只能手动匹配弹幕。

这个项目的初衷就是为了弥补我在使用[tsukimi emby播放器的时候无法加载弹幕的遗憾](https://github.com/tsukinaha/tsukimi/issues/51#issuecomment-2081051829)，所以自己开发的。之后的其他自动加载弹幕功能什么的，都是别的在本地看番的用户有需求所以加上的。

**Comment by thouser8** [comment]
> > 我试了一下，发现本项目和这个项目https://github.com/Kosette/danmaku 是可以兼容的👍但是本项目还不支持emby网络播放对吗
> 
> 是支持emby网络播放的。只要能调用mpv，并且可以使用自己的自定义配置就能够使用本插件。但是在emby在线播放的时候不支持使用全自动弹幕加载和记忆功能，只能手动匹配弹幕。
> 
> 这个项目的初衷就是为了弥补我在使用[tsukimi emby播放器的时候无法加载弹幕的遗憾](https://github.com/tsukinaha/tsukimi/issues/51#issuecomment-2081051829)，所以自己开发的。之后的其他自动加载弹幕功能什么的，都是别的在本地看番的用户有需求所以加上的。

那可能我有别的插件或者设置项冲突了，这个插件添加到我本地自行配置的mpv里就没法支持emby（按了没反应）。然后我单独用了下别人提供的含有本插件的mpv整合包，这样用又是支持emby的。有没有办法能够排查出到底是哪里冲突了吗

**Comment by Tony15246** [comment]
> 那可能我有别的插件或者设置项冲突了，这个插件添加到我本地自行配置的mpv里就没法支持emby（按了没反应）。然后我单独用了下别人提供的含有本插件的mpv整合包，这样用又是支持emby的。有没有办法能够排查出到底是哪里冲突了吗

这个有不少可能的原因，比如说和别的插件冲突，和其他已有的设置项冲突，或者在windows平台下插件的兼容性问题（我开发使用的是linux），有点难猜。有出现问题时的日志的话，我可以试试排查看看。

我有空的时候也在同学的windows电脑上试试看有没有类似的问题。

**Comment by Tony15246** [comment]
对了，之前有个版本在打开load_local_danmaku选项的时候确实会出现emby里没法使用插件的问题。主分支里修复了这个bug，但是还没有加到最新的release里，因为我想多修一点bug在发布一个更stable的release。如果你用的不是主分支git最新版，而是从release里下载的话，克隆最新的主分支的代码应该就能解决这个问题。我也会尽快发布最新版的release。

**Comment by thouser8** [comment]
> 对了，之前有个版本在打开autoload_local_danmaku选项的时候确实会出现emby里没法使用插件的问题。主分支里修复了这个bug，但是还没有加到最新的release里，因为我想多修一点bug后，再发布一个更stable的release。如果你用的不是主分支git最新版，而是从 v1.1.0 版的release里下载的话，确实会有这个问题，克隆最新的主分支的代码应该就能解决这个问题（或者直接在网页上下载最新的api.lua和main.lua直接替换本地的文件就行）。我也会尽快发布最新版的release。

用了最新版确实没问题了，再次感谢哈🩷

**Comment by Tony15246** [comment]
> 然后我单独用了下别人提供的含有本插件的mpv整合包，这样用又是支持emby的。

不用谢。btw，你说的这个mpv整合包是dyphire大佬的mpv-config整合包吗？我都不知道大佬收录了我这个小插件😂

**Comment by thouser8** [comment]
> > 然后我单独用了下别人提供的含有本插件的mpv整合包，这样用又是支持emby的。
> 
> 不用谢。btw，你说的这个mpv整合包是dyphire大佬的mpv-config整合包吗？我都不知道大佬收录了我这个小插件😂
https://t.me/framedrop5/109，是这个频道主根据dyphire大佬的整合包改的自用配置啦。他也是某公益二次元emby服管理，在群里推荐过你这个项目哈哈🙂

**Comment by Tony15246** [comment]
> https://t.me/framedrop5/109
> 是这个频道主根据dyphire大佬的整合包改的自用配置啦。他也是某公益二次元emby服管理，在群里推荐过你这个项目哈哈🙂

原来如此。

我看了一下频道消息，有好几个人都遇到了我之前已经修好的bug，看来得快点发布最新版release了🥲
