### ISSUE TITLE
[BUG]检索结果存在重复以及个别网络剧集未能正确找到弹幕

### ISSUE THREAD

**Issue by thouser8** [Tony15246/uosc_danmaku#18]
使用的是最新realease
1.
![image](https://github.com/user-attachments/assets/9f3c8ce6-001b-4d91-982e-fe5445797c4b)

2.有些emby剧集会匹配不到弹幕，
![image](https://github.com/user-attachments/assets/3cbfdb5b-1860-478c-bf35-3087d2918a5f)
而换用其他项目则能正确匹配到弹幕：
![image](https://github.com/user-attachments/assets/24df227f-3bf4-4f86-ab25-a9902a503471)

**Comment by Tony15246** [comment]
> 使用的是最新realease
> 
> 1.
> 
> ![image](https://github.com/user-attachments/assets/9f3c8ce6-001b-4d91-982e-fe5445797c4b)
> 
> 
> 
> 2.有些emby剧集会匹配不到弹幕，
> 
> ![image](https://github.com/user-attachments/assets/3cbfdb5b-1860-478c-bf35-3087d2918a5f)
> 
> 而换用其他项目则能正确匹配到弹幕：
> 
> ![image](https://github.com/user-attachments/assets/24df227f-3bf4-4f86-ab25-a9902a503471)
> 
> 

出现问题的两部番剧的名字和是第几集能告诉我一下吗？我尝试复现一下看看是什么问题

**Comment by thouser8** [comment]
> 
> 出现问题的两个图片里的番剧是什么名字和是第几集能告诉我一下吗？我尝试复现一下看看是什么问题

到了联谊会上发现连一个女生也没有，第二集

**Comment by Tony15246** [comment]
检索结果重复不是bug，是弹弹play的库里面真的有两个名字一模一样的作品。😂
```
{
      "animeId": 18228,
      "bangumiId": "18228",
      "animeTitle": "到了联谊会上发现连一个女生都没有",
      "type": "tvseries",
      "typeDescription": "TV动画",
      "imageUrl": "https://img.dandanplay.net/anime/18228_medium.jpg",
      "startDate": "2024-09-30T00:00:00",
      "episodeCount": 12,
      "rating": 5.3,
      "isFavorited": false
    },
    {
      "animeId": 35417,
      "bangumiId": "35417",
      "animeTitle": "到了联谊会上发现连一个女生都没有",
      "type": "jpdrama",
      "typeDescription": "日本电视剧",
      "imageUrl": "https://img.dandanplay.net/anime/35417.jpg",
      "startDate": "2022-10-20T00:00:00",
      "episodeCount": 10,
      "rating": 0,
      "isFavorited": false
    }
```

**Comment by Tony15246** [comment]
未找到弹幕文件那个问题，你本地bin文件夹目录下面的`DanmakuFactory.exe`这个文件还在吗，有没有被windows删掉？参考这个readme文件最后的这个

https://github.com/Tony15246/uosc_danmaku?tab=readme-ov-file#%E6%88%91%E5%9C%A8windows%E5%B9%B3%E5%8F%B0%E4%B8%8A%E4%BD%BF%E7%94%A8%E6%AD%A4%E6%8F%92%E4%BB%B6%E6%80%BB%E6%98%AF%E4%BC%9A%E6%98%BE%E7%A4%BA%E6%9C%AA%E6%89%BE%E5%88%B0%E5%BC%B9%E5%B9%95%E6%96%87%E4%BB%B6

**Comment by thouser8** [comment]
> 未找到弹幕文件那个问题，你本地bin文件夹目录下面的`DanmakuFactory.exe`这个文件还在吗，有没有被windows删掉？参考这个readme文件最后的这个
> 
> https://github.com/Tony15246/uosc_danmaku?tab=readme-ov-file#%E6%88%91%E5%9C%A8windows%E5%B9%B3%E5%8F%B0%E4%B8%8A%E4%BD%BF%E7%94%A8%E6%AD%A4%E6%8F%92%E4%BB%B6%E6%80%BB%E6%98%AF%E4%BC%9A%E6%98%BE%E7%A4%BA%E6%9C%AA%E6%89%BE%E5%88%B0%E5%BC%B9%E5%B9%95%E6%96%87%E4%BB%B6

![image](https://github.com/user-attachments/assets/6b911df2-e1cd-401b-8884-6e5f49fef903)
在的

**Comment by Tony15246** [comment]
不是这个问题的话，那只有查看mpv日志才能进一步判断了

**Comment by Tony15246** [comment]
> 不是这个问题的话，那只有查看mpv日志才能进一步判断了

能把出现问题的时候mpv的log文件发给我看一下吗？

**Comment by thouser8** [comment]
> > 不是这个问题的话，那只有查看mpv日志才能进一步判断了
> 
> 能把出现问题的时候mpv的log文件发给我看一下吗？

我好像找到原因了，是uosc_danmaku.conf配置文件里我直接复制粘贴了DanmakuFactory_Path=/path/to/your/DanmakuFactory。。。尴尬

**Comment by Tony15246** [comment]
> 我好像找到原因了，是uosc_danmaku.conf配置文件里我直接复制粘贴了DanmakuFactory_Path=/path/to/your/DanmakuFactory。。。尴尬

哈哈哈，常有的事

每个程序员都会犯憨憨的错误😆

**Comment by Tony15246** [comment]
> 到了联谊会上发现连一个女生也没有，第二集

这部番预告刚出的时候我老想看了，当时特别期待。没想到现在出了两集了都，都没看到有这部番更新的消息，没想到今天在github issue里被提醒了。

**Comment by thouser8** [comment]
> > 到了联谊会上发现连一个女生也没有，第二集
> 
> 这部番预告刚出的时候我老想看了，当时特别期待。没想到现在出了两集了都，都没看到有这部番更新的消息，没想到今天在github issue里被提醒了。

哈哈，十月份这些动画好像都有乱七八糟的先行之类的，更新很不规律，给我班固米维护追更都打乱了。
顺便我刚刚看到hire大佬给你拉了个pr，是能够支持emby也能自动搜索弹幕的功能吗？

**Comment by Tony15246** [comment]
> 顺便我刚刚看到hire大佬给你拉了个pr，是能够支持emby也能自动搜索弹幕的功能吗？

不完全是。自动搜索弹幕功能需要番剧的标题和番剧的文件前15MB数据计算出来的哈希码。

这个pr及其相关的维护具体实现的功能是，在线（比如说在某个emby服）看某部番剧的时候，第一次看这部番的时候使用手动搜索会自动填充这部番的名字，可以不用自己输入。之后再看这部番的任意其他集数的时候，会自动推理是这部番的第几集，这时候就能自动加载了。相当于每部番需要手动加载一次，不是完全全自动。

现在对于本地文件，由于可以轻松计算文件前15兆的哈希，已经实现了全自动加载（偶尔可能识别错误，这时候需要手动介入人工加载），只要把同一部番的内容放在同一个文件夹下就能全部自动加载。

**Comment by thouser8** [comment]
> > 顺便我刚刚看到hire大佬给你拉了个pr，是能够支持emby也能自动搜索弹幕的功能吗？
> 
> 不完全是。自动搜索弹幕功能需要番剧的标题和番剧的文件前15MB数据计算出来的哈希码。对于在线播放这种形式，暂时还没有能够实现计算数据流。
> 
> 这个pr及其相关的维护具体实现的功能是，在线（比如说在某个emby服）看某部番剧的时候，第一次看这部番的时候使用手动搜索会自动填充这部番的名字，可以不用自己输入。之后再看这部番的任意其他集数的时候，会自动推理是这部番的第几集，这时候就能自动加载了。相当于每部番需要手动加载一次，不是完全全自动。
> 
> 现在对于本地文件，由于可以轻松计算文件前15兆的哈希，已经实现了全自动加载（偶尔可能识别错误，这时候需要手动介入人工加载），只要把同一部番的内容放在同一个文件夹下就能全部自动加载。

了解了，这样也足够方便了。
