### ISSUE TITLE
请问简单的自动化功能可以实现吗？

### ISSUE THREAD

**Issue by Lyzd1** [Tony15246/uosc_danmaku#2]
比如将某一文件夹内播放的视频文件获取的剧集名称收集保存下来；下次同一文件夹下的视频文件使用搜索功能时，可以自动填充该信息，直接进入选择剧集信息界面，如下图所示，从而不需要每次都一步步的输入信息。
![image](https://github.com/user-attachments/assets/d11970de-2d14-40d2-ae3e-eb8d5163b526)
当然，更进一步就是将集数（本地文件名是第21集）与弹弹play的集数（第二季度第1集）做一个绑定，实现全自动化加载。

大佬有时间的话，可以实现一下。当然如果太忙，也就算了，毕竟现在也是相当棒了！！！

**Comment by Tony15246** [comment]
非常感谢你对我的插件的使用和支持！我把代码传到GitHub上的时候还以为这个仓库会和我的其他仓库一样无人问津呢😭

其实我在一开始实现这个插件的时候，想过是否要使用通过文件名自动匹配的方式进行自动加载，不过最终没有通过这种方式实现。其实这也好理解，因为某一文件夹内的本地视频文件往往是通过在网上找的资源下载的，文件名包含太多冗余以及误导性信息（比如翻译的字幕组的名称、以及视频画质、字幕语言等等信息），几乎搜索不出来有用的结果。比如说像这样的标题`[Nekomoe kissaten][GIRLS BAND CRY][01][1080p][JPSC]`，实际有用的部分只有`GIRLS BAND CRY`和`01`，但视频文件的标题命名本来没有统一的命名标准，自然也没法通过一个正则表达式精准提取出需要的信息。更别提如果在通过mpv播放器流式播放浏览器或者emby服务器上的视频的时候，很有可能根本获取不到视频的标题，又或者获取到的标题信息完全就是错误的，和视频完全没有关联。

当然，我没有实现自动化加载的另一个原因是，这个功能其实已经有人实现了，直接和我的插件叠加使用即可。[dyphire](https://github.com/dyphire)等大佬实现了[基于文件名和文件哈希值匹配弹弹play弹幕](https://github.com/rkscv/danmaku)：https://github.com/rkscv/danmaku
由于我上面提到的通过视频文件名匹配这个方法天然存在的缺陷，我猜测这种匹配弹幕的方法准确率有可能不尽人意（当然也可能大佬们的代码经过精心优化已经克服了我所提到的困难，其实准确率很高）。所以我在实现插件的时候放弃了一些用户使用时候的便利性，来换取搜索匹配的准确性（毕竟是用户自己手动选择的，用户肯定清楚地知道有没有选中正确的番剧和剧集）。

所以如果你需要自动化加载弹幕的话，可以考虑使用先使用[基于文件名和文件哈希值匹配弹弹play弹幕](https://github.com/rkscv/danmaku)，如果发现自动化匹配到的弹幕不正确，再关闭自动匹配的弹幕，使用我的插件手动搜索并重新加载弹幕。

很抱歉自动化加载弹幕暂时不在本插件的实现计划中。不过通过上面描述的办法或许可以等效地满足你的需求。

**Comment by Tony15246** [comment]
这个功能确实可以大大提高便利性，我空闲的时候可以考虑实现一下，不过我现在忙于复习考研，恐怕抽不出来太大段的空闲，只能随缘更新了😂

**Comment by Lyzd1** [comment]
> 非常感谢你对我的插件的支持和肯定！这个插件主要是我自己和身边的同学在使用，我本来上传代码的时候还以为这个插件不会有什么人关注和使用(ㄒoㄒ)
> 
> 这个功能实现起来不会太难。创建一个文件记录所有播放过的本地文件的路径以及其与弹弹play中episodeID的对应关系，每次加载时读取查询即可。
> 
> 这个功能确实可以大大提高便利性，我空闲的时候可以考虑实现一下，不过我现在忙于复习考研，恐怕抽不出来太大段的空闲，只能随缘更新了😂

是的，随缘就好。感谢您将代码上传！

**Comment by Tony15246** [comment]
这个自动化功能比想象中实现起来要简单。刚才回寝休息以后稍微捣鼓了一小会儿，测试了一下暂时没发现什么问题。修改已经推送到主分支，你可以拉取下来试试看，使用过程中遇到什么bug的话可以开新issue提出。

由于流式播放的网络视频地址或者原数据总是有微妙的变动，目前这个自动化功能只能对本地播放的视频文件生效，对于调用mpv进行在线播放的视频无法生效。
