### ISSUE TITLE
请求Segoe UI Emoji支持彩色显示

### ISSUE THREAD

**Issue by wan0ge** [Tony15246/uosc_danmaku#27]
来提一个锦上添花的功能，如果实现起来很困难那就算了
突然发现Emoji不支持彩色显示，弹弹play也是，[ani这个项目](https://github.com/open-ani/ani)用奇怪的方法支持了
![image](https://github.com/user-attachments/assets/a8ff4ed4-5175-47df-a599-201cf8aa1089)
![image](https://github.com/user-attachments/assets/bb76a3c2-ffc6-48cd-8322-7c930aee45eb)

**Comment by dyphire** [comment]
libass 不支持渲染彩色字体

**Comment by Tony15246** [comment]
彩色emoji确实技术难度太大。ani能实现这种渲染图片并移动的方式，应该本身也是基于播放器本身也经过了其自己开发和魔改。这种程度的实现超过了一个插件的能力范围，而且实现难度远大于了这个功能的意义，暂不列入开发计划内。

**Comment by hooke007** [comment]
> ani这个项目用奇怪的方法支持了

兄弟，槽点太大了。就不说这玩意和mpv毫无关系了。
人家连弹幕引擎都是[手搓的](https://github.com/open-ani/animeko/pull/836)，这有啥参考价值。

**Comment by wan0ge** [comment]
> 
> 兄弟，槽点太大了。就不说这玩意和mpv毫无关系了。 人家连弹幕引擎都是[手搓的](https://github.com/open-ani/animeko/pull/836)，这有啥参考价值。

我不懂代码，我只知道ani实现了其他弹幕播放器都没有实现

**Comment by wan0ge** [comment]
https://github.com/hihkm/DanmakuFactory/commit/4af38bde3da222d3a1a91281eba8265dc9447c1e 【feat(ass): 支持转义 emoji Unicode 码位】
看到上游支持转义了，默默问下我们是卡在渲染还是不能实现是吗👀

**Comment by hooke007** [comment]
最终上游是 libass ，而不是其他的项目 https://github.com/libass/libass/issues/381

**Comment by wan0ge** [comment]
> 最终上游是 libass ，而不是其他的项目 [libass/libass#381](https://github.com/libass/libass/issues/381)

原来如此
