### ISSUE TITLE
自动化增强

### ISSUE THREAD

**Issue by Lyzd1** [Tony15246/uosc_danmaku#3]
您好，首先很感谢大佬能够抽空做这样一个自动化部分。

但是对于该部分我有些其他想法您能看看。
1.弹幕开关设置**全局记忆功能**：当我关闭弹幕和mpv后，再次打开该视频，我希望弹幕保持上次开/关的状态，但遗憾的是，mpv自动开启了弹幕，mpv并没有记住它。~~

2.**自动化增强部分**
  很抱歉的上一个issue我并没有表述准确，我为此感到抱歉。下面两个部分，是我最开始的想法和看到弹弹id后的想法。
  

**半自动装填参数**
动漫有三个部分：名字+季度+集数。
当时我希望将当前视频文件的父文件名与手动匹配的动漫名和季度作为一个索引参数保存，当打开该父文件夹下所有视频文件并且使用搜索功能时，直接通过该索引保留参数进入集数选择页面。
即首先做一个父文件名判断，如果索引存在，则前两部分参数自动填入，否则一步步选择信息后，添加索引参数并保存。

**全自动装填弹幕：**
但在我体验新版本过程中，观察到同一部动漫指定季度的对应集数所获取episode id时，我相信上述实现起来会更简单。id的规律是：同一部动漫指定季度，第一集末尾id都是1，第12集是12，是递增的。比如 第1集是188010001 ，第12集是188010012。
那么可以将动漫与episode id进行一定绑定，每一部动漫只需要一个索引。动漫突出两个元素：名字+集数，名字作为索引前缀，集数和episode id进行绑定，索引前缀用来定位，集数规定为参考集数。
当打开一个新视频，首先动漫名与索引前缀进行对比，在索引文件中找到匹配的episode id；其次，应该可以通过正则表达式之类找到集数，并与参考集数做对比，算出差值；最后将” episode id = 差值+episode id “，就实时自动获取同一父文件名下所有视频文件的弹幕啦。（当然我感觉父文件名也可以作为前缀，看那个方便)。

最后的最后，我主要是纸上谈兵，大佬还是学业为重，空出时间随便写写就好，当休闲了。感谢！^^

**Comment by Tony15246** [comment]
弹幕开关全局记忆功能和半自动装填参数功能实现起来存在一定工作量，不过都有肯定能行得通的实现思路。我会在后面更新中加上这两个功能。

**Comment by Tony15246** [comment]
难办的是全自动装填弹幕。因为这一步很难做到

> 其次，应该可以通过正则表达式之类找到集数

没有办法通过正则表达式找到集数，因为正则表达式说白了就是一个有限状态机，规定了一种正则文法。但是视频标题的命名是不会遵循一种特定的文法的。比如说以下是我从我的本地资源库里随便选的几个视频标题

```
KitaujiSub_Make_Heroine_ga_Oosugiru!_01WebRipHEVC_AACCHS_JP
Avataro.Sentai.DonBrothers.EP01.HD1080P.CHS.V2
[AI-Raws&ANK-Raws] ぼっち・ざ・ろっく！ #01 (BD HEVC 1920x1080 yuv444p10le FLAC)[25F9E8E6]
[XKsub][Oshi no Ko][01V2][CHS][1080P][WEBrip][MP4]
```

完全没有任何规律可言，更不可能遵循同一种文法，这也很正常，因为不可能有人指定一个RFC标准要求全世界的视频按照一种标准来命名。但是人就是能看懂这样的标题，能知道这样的标题是第几集。所以如果我的插件能接入可以模拟人的智能的——自然语言处理人工智能模型，那就有办法识别标题说的是第几集了。但是目前对我来说想要通过一个lua脚本调用一个预训练的大模型，我的知识储备还不太够😂

**Comment by Lyzd1** [comment]
> 难办的是全自动装填弹幕。因为这一步很难做到
> 
> > 其次，应该可以通过正则表达式之类找到集数
> 
> 没有办法通过正则表达式找到集数，因为正则表达式说白了就是一个有限状态机，规定了一种正则文法。但是视频标题的命名是不会遵循一种特定的文法的。比如说以下是我从我的本地资源库里随便选的几个视频标题
> 
> ```
> KitaujiSub_Make_Heroine_ga_Oosugiru!_01WebRipHEVC_AACCHS_JP
> Avataro.Sentai.DonBrothers.EP01.HD1080P.CHS.V2
> [AI-Raws&ANK-Raws] ぼっち・ざ・ろっく！ #01 (BD HEVC 1920x1080 yuv444p10le FLAC)[25F9E8E6]
> [XKsub][Oshi no Ko][01V2][CHS][1080P][WEBrip][MP4]
> Cyberpunk.Edgerunners_1080P_01
> ```
> 
> 完全没有任何共同的规律可言，更不可能遵循同一种文法，这也很正常，因为不可能有人指定一个RFC标准要求全世界的视频按照一种标准来命名。但是人就是能看懂这样的标题，能知道这样的标题是第几集。所以如果我的插件能接入可以模拟人的智能的——自然语言处理人工智能模型，那就有办法识别标题说的是第几集了。但是目前对我来说想要通过一个lua脚本调用一个预训练的大模型，我的知识储备还不太够😂

搞了一天。看着倒是可行了。json扩展名改成lua 。
[api.json](https://github.com/user-attachments/files/17005582/api.json)

那个正则表达式是ai搞的，测试了一下还可以

**Comment by Tony15246** [comment]
> 那个正则表达式是ai搞的，它那个使用了个循环的思路，多次找数字，直到找到合适的集数。测试了一下还可以。后面再测试修改修改。^^

确实，我有点追求完美主义了~写算法题写的，总是在思考让算法能够覆盖所有刁钻的样例~，实际问题中大部分情况下可用就能算得上是可用了。筛出所有数字，再排除1080p和4k的干扰，确实能够保证绝大多数正常情况下拿到正确的集数了。修改后的api.lua的代码我阅读了一下，没有什么问题，写的很好( • ̀ω•́ )👍

如果你想当个contributer的话，可以fork我的仓库，改完代码以后，向我的仓库提出pull request，我来合并代码。如果想深藏功与名的话，也可以等我晚上回寝室手动整合（๑ • ‿ • ๑ ）你准备采取哪种方式？

**Comment by Lyzd1** [comment]
> > 那个正则表达式是ai搞的，它那个使用了个循环的思路，多次找数字，直到找到合适的集数。测试了一下还可以。后面再测试修改修改。^^
> 
> 确实，我有点追求完美主义了~写算法题写的，总是在思考让算法能够覆盖所有刁钻的样例~，实际问题中大部分情况下可用就能算得上是可用了。筛出所有数字，再排除1080p和4k的干扰，确实能够保证绝大多数正常情况下拿到正确的集数了。修改后的api.lua的代码我阅读了一下，没有什么问题，写的很好( • ̀ω•́ )👍。这样的话，半自动装填参数其实就没必要实现了，直接用这个全自动装填弹幕就行。
> 
> 如果你想当个contributer的话，可以fork我的仓库，改完代码以后，向我的仓库提出pull request，我来合并代码。如果想深藏功与名的话，也可以等我晚上回寝室手动整合（๑ • ‿ • ๑ ）你准备采取哪种方式？

okok, 我提交了申请。那我得自己动手实操一下下。哈哈。

**Comment by Tony15246** [comment]
@Lyzd1 我稍微调整了一下合并后的代码，增强了一下代码的鲁棒性并解决了一下Linux系统下的兼容性问题。

有一个重要调整是全自动装填弹幕功能被我设置成了一个配置项，默认是关闭状态，需要在`script-opts`下的`uosc_danmaku.conf`文件中添加`auto_load=yes`才会启用全自动装填弹幕功能。这么做一来是因为这个功能目前还算是在实验阶段，说不定会产生影响插件正常运行的问题，因此设置为可选配置项，保证插件至少能正常运行基本功能。二来，是因为存储剧集对应代码信息的`history.json`文件从原本的一个层级变成了两个层级，解析JSON文件的时间复杂度大幅上升，加载弹幕的体感延迟时间明显增加，因此把全自动装填弹幕功能设置为了默认关闭的配置项，让用户自己选择是否要用更长的加载时间换取更便利的加载方式。

**Comment by Lyzd1** [comment]
> @Lyzd1 我稍微调整了一下合并后的代码，增强了一下代码的鲁棒性并解决了一下Linux系统下的兼容性问题。
> 
> 有一个重要调整是全自动装填弹幕功能被我设置成了一个配置项，默认是关闭状态，需要在`script-opts`下的`uosc_danmaku.conf`文件中添加`auto_load=yes`才会启用全自动装填弹幕功能。这么做一来是因为这个功能目前还算是在实验阶段，说不定会产生影响插件正常运行的问题，因此设置为可选配置项，保证插件至少能正常运行基本功能。二来，是因为存储剧集对应弹幕信息的`history.json`文件从原本的一个层级变成了两个层级，解析JSON文件的时间复杂度大幅上升，加载弹幕的体感延迟时间明显增加，因此把全自动装填弹幕功能设置为了默认关闭的配置项，让用户自己选择是否要用更长的加载时间换取更便利的加载方式。


感谢大佬  😄。没问题没问题。基本上已经是完全体了。最后可以再对写入文件进行一个分流。

--	写入history和读取弹幕库
--	对不同调用模式进行分流。
function set_episode_id(input,from_menu)   --设置为菜单建立
	from_menu = from_menu or false  --如果为true，则使用下面逻辑。如果为false，则不修改数据，仅加载。
    episodeId = tonumber(input)
	  
	
	-- 如果来自菜单加载弹幕，正常写入
	if from_menu then 
		local fname = get_father_directory()	--获取父文件名
		if fname ~= nil then
			local history_path = danmaku_path .. "history.json"  
			local episodeNumber=get_episode_number()   
			local history_json = read_file(history_path)
			if history_json ~= nil then
				local history = utils.parse_json(history_json)
				history[fname] = {}
				history[fname].episodeNumber=episodeNumber
				history[fname].episodeId = episodeId
				write_json_file(history_path, history)
			else
				local history = {}
				history[fname] = {}
				history[fname].episodeNumber=episodeNumber
				history[fname].episodeId = episodeId
				write_json_file(history_path, history)
			end
		end
	end	
	

	-- 读取episodeID去获取弹幕
	if options.load_more_danmaku then
			fetch_danmaku_all(episodeId) 
		else
			fetch_danmaku(episodeId)
		end

end

**Comment by Tony15246** [comment]
> 最后可以再对写入文件进行一个分流。

确实，这么干的话，可以在自动填装弹幕的时候减少一次解析JSON的时间，此改进已推送到主分支并实装。弹幕开关设置全局记忆功能也已在提交f917734中实现。至此自动化增强部分功能均实装。

**Comment by Lyzd1** [comment]
> > 最后可以再对写入文件进行一个分流。
> 
> 确实，这么干的话，可以在自动填装弹幕的时候减少一次解析JSON的时间，此改进已推送到主分支并实装。弹幕开关设置全局记忆功能也已在提交f917734中实现。至此自动化增强部分功能均实装。

在使用时，又发现这个查找集数有点问题了。在get_episode_number中，filename:find(number)函数可能出现错误。比如xxx-2024-4k-5.mp4 中，在循环查找4这个数字时，会找到2024中的4，导致4被识别为集数。
同时在我使用时发现filename:sub（x,y+#number+1）函数是从 x 索引到 y+#number+1 索引，会多1位，需要修改为filename:sub（x,y+#number）

对于上述两个问题，我修改如下：

```
-- 获取当前文件名所包含的集数
function get_episode_number()
    local filename = mp.get_property("filename")
    local pattern = "(%d+)"
	local flagindex=1  
	
    -- 尝试匹配文件名中的数字
    for number in string.gmatch(filename, pattern) do
	    
        -- 数字转换和文件名大小写转换
        local episodeNumber = tonumber(number)
        filename = string.lower(filename)
		local startindex,endindex=string.find(filename,number,flagindex)  --获取当前数字,从flagindex处索引开始查找（防止重复）
		flagindex=endindex+1
		
		-- 判断数字是否合理
        if episodeNumber and episodeNumber <= 1000 then
			local getstring = filename:sub(startindex, endindex + 1) -- 获取清晰度
			--local getstring2 = filename:sub(startindex, endindex + 2) -- 获取季度2nd
			--local getstring3 = filename:sub(startindex - 1, endindex)  -- 获取季度s2

			if getstring ~= "4k" and getstring ~= "720p" and getstring ~= "360p"	   
			--and getstring2 ~= "2nd" 
			--and getstring2 ~= "3rd"
			--and getstring3 ~= "s4" 
			then
				return(episodeNumber)
			end
		end
    end
end 

```

吐槽一下，这个季度数是没办法了，也只能一个个单独列出来，感觉太多了可能会影响速度。所以算我自用的。~~

**Comment by Tony15246** [comment]
确实，这两个问题我花一个提交修复一下
