### ISSUE TITLE
[建议]显示当前匹配的弹幕详情

### ISSUE THREAD

**Issue by wan0ge** [Tony15246/uosc_danmaku#34]
自动匹配弹幕有匹错的情况，但是不会显示匹的是哪一集哪个剧，会不好判断

**Comment by Tony15246** [comment]
> 自动匹配弹幕有匹错的情况，但是不会显示匹的是哪一集哪个剧，会不好判断

确实，这样会不方便

你是更喜欢每次加载完弹幕以后显示一下加载的是哪部番哪一集的弹幕（这种方式的问题就是没注意漏看了的话就没法重新查看了）；还是使用弹幕开关来开关弹幕的时候都会显示当前弹幕是哪部番第几集（这种方法的优点是可以随时查看）；还是说上面两种一起实现？

**Comment by wan0ge** [comment]
> 
> 确实，这样会不方便
> 
> 你是更喜欢每次加载完弹幕以后显示一下加载的是哪部番哪一集的弹幕（这种方式的问题就是没注意漏看了的话就没法重新查看了）；还是使用弹幕开关来开关弹幕的时候都会显示当前弹幕是哪部番第几集（这种方法的优点是可以随时查看）；还是说上面两种一起实现？

我觉得一起实现好一些（）毕竟弹幕开关方式要手动开关一次才能显示吧，，要是能找个地方常显就好了，文件标题显示那边能够改动吗

**Comment by Tony15246** [comment]
改文件标题也可以，虽然要重构一部分代码和功能，因为之前部分代码依赖写死的文件标题。

那就按照改文件标题的方式来实现吧，这种方法确实是最直观的。

**Comment by dyphire** [comment]
PR #35 应该完美解决了这个问题

**Comment by Tony15246** [comment]
> 改文件标题的想法太侵入性了，还可能破坏其他脚本的功能。

我在按照改文件标题的思路来实现的时候确实也遇到了困难。由于mpv对于tracks的属性的记录太少，又把视频、音频、字幕三种track的id混在一起，导致没有一个确定的标题的话弹幕轨道将难以跟踪。改文件标题将影响到移除、添加弹幕轨道等基本功能。同时动画和剧集标题中可能存在的非法字符，也可能导致弹幕文件因为非法文件名出现各种问题。改文件标题确实还是太risky了。

@wan0ge 抱歉，出于代码鲁棒性以及插件稳定性的考量，将不采用修改弹幕文件标题的实现方式。预计合并PR #35 的代码，采用的是`每次加载完弹幕以后显示一下加载的是哪部番哪一集的弹幕`的实现方式。如dyphire所说，如果漏看了 OSD 消息可以通过打开控制台来查看弹幕关联结果。

**Comment by wan0ge** [comment]
其实我没想到是真改文件标题(汗，我原本的意思是，显示在文件标题区域的后面（不修改原文件），我问的能不能改意思是脚本能够做到在那边添加东西吗，我的表达问题我的(汗
不过不管怎样现在实现了就行👍
