### ISSUE TITLE
无法使用中文输入及图形化界面弹幕样式设置

### ISSUE THREAD

**Issue by thcehocai** [Tony15246/uosc_danmaku#36]
我使用的是mpv.net版本，动画名称搜索栏无法输入中文，只能输入英文，但是粘贴是可以的，mpv.net自己的播放列表搜索栏可以正常输入中文，请问有什么办法解决吗？
另外 如果能把弹幕设置弄个图形化界面就好了 但是好像更改之后也得重启mpv才能生效 不知道能不能做到即改即生效

**Comment by Tony15246** [comment]
mpv.net的原生搜索栏能正常输入中文应该是mpv.net自己实现的中文支持。这个问题大概率是上游bug，属于uosc UI框架和mpv.net播放器之间的兼容性问题。可以去向上游提issue。

我自己也由于mpv播放器在linux系统上没有IME支持,在mpv播放器的任何地方都没法输入中文，只能靠复制粘贴。😂我之前提的discussion还在这呢https://github.com/mpv-player/mpv/discussions/14775

**Comment by Tony15246** [comment]
关于图形化界面设置弹幕的问题。目前uosc UI框架提供的菜单api在我看来暂时还不适合完成一套符合正常交互逻辑的弹幕设置图形化界面。

**Comment by dyphire** [comment]
这其实是一个 mpv.net 的问题，它只在自己实现的 UI 输入框架活跃时允许启用 IME，其他状态会禁用所以第三方脚本无法使用 IME
去向 mpv.net 提出功能请求以放开对 IME 的不必要限制

> 
> 我自己也由于mpv播放器在linux系统上没有IME支持,在mpv播放器的任何地方都没法输入中文，只能靠复制粘贴；而在windows上就完全没有这个问题，因为mpv有windows的IME支持。😂我之前提的discussion还在这呢[mpv-player/mpv#14775](https://github.com/mpv-player/mpv/discussions/14775)

mpv 在 Windows 上的 IME 支持也是去年年底才加的，此前由于不支持 IME 逼得我为 uosc 实现了罗马化拼音搜索（
linux 的话前不久 mpv 好像为 x11 实现了 IME：https://github.com/mpv-player/mpv/pull/15077 ，mac 上仍不支持

**Comment by thcehocai** [comment]
如果能实现拼音首字母搜索就好了

**Comment by Tony15246** [comment]
> 如果能实现拼音首字母搜索就好了

理论上不太可行，毕竟插件只是把用户输入发给弹弹play的api，并不是真的有可以拿来匹配首字母拼音的所有动画名称的数据。弹弹play的api不支持拼音首字母搜索，我也没办法添加拼音首字母搜索支持。

> linux 的话前不久 mpv 好像为 x11 实现了 IME

由于我使用linux系统，且个人更偏爱wayland，我其实也没法在mpv中输入中文。我平时的解决方案就是输入日语罗马音搜索。另外用动画的英文名进行搜索也是支持的。

**Comment by hooke007** [comment]
> mac 上仍不支持

Mac一直都支持IME

**Comment by thcehocai** [comment]
想请问一下目前支持从哪些弹幕源抓取弹幕？能否手动选择需要抓取的弹幕源呢？

**Comment by Tony15246** [comment]
目前弹幕源选择支持三种模式，默认情况下正常通过弹弹play的获取弹幕api获取弹幕；开启`load_more_danmaku`选项加载弹弹play数据库中记录的与当前视频有关的所有弹幕源的所有弹幕；使用`从弹幕源添加弹幕`功能手动添加弹幕源并自动加载该弹幕源下的弹幕。具体功能和使用readme文件里都有写。

**Comment by wan0ge** [comment]
问一下输入框无法用左右箭头移动输入光标位置也是上游问题吗，沟槽的挺难用的输入框…

**Comment by hooke007** [comment]
https://github.com/tomasklaen/uosc/issues/766
只是uosc的菜单不支持

**Comment by wan0ge** [comment]
> 
> 你很依赖光标的话可以用控制台的实现（

恐怕比较难实现我需求吧，如果场景是想移动光标修改粘贴上去文字应该能控制台那边调用插件实现？但这种获取文件标题预输入的文本没法靠控制台改吧
![image](https://github.com/user-attachments/assets/8e84cef9-1c99-4bc4-9f05-5f04b226e120)

**Comment by dyphire** [comment]
> > linux 的话前不久 mpv 好像为 x11 实现了 IME
> 
> 由于我使用linux系统，且个人更偏爱wayland，我其实也没法在mpv中输入中文。我平时的解决方案就是输入日语罗马音搜索。另外用动画的英文名进行搜索也是支持的。并且插件现在也实现了匹配视频文件名，尽可能自动填充动画名称，可能不会太经常需要手动输入。

mpv 对 wayland 的 IME支持要来了：  https://github.com/mpv-player/mpv/pull/15707

**Comment by dyphire** [comment]
> 问一下输入框无法用左右箭头移动输入光标位置也是上游问题吗，沟槽的挺难用的输入框…

uosc 上游已支持输入框中的光标移动：https://github.com/tomasklaen/uosc/commit/77cb8bb1a17594991b62940d76c4cf363183ecd8
该实现目前在中文等 utf-8 多字节字符的使用场景下存在 bug，我已提交相应 pr 修复此问题：https://github.com/tomasklaen/uosc/pull/1102

**Comment by wan0ge** [comment]
> 
> uosc 上游已支持输入框中的光标移动：[tomasklaen/uosc@77cb8bb](https://github.com/tomasklaen/uosc/commit/77cb8bb1a17594991b62940d76c4cf363183ecd8) 该实现目前在中文等 utf-8 多字节字符的使用场景下存在 bug，我已提交相应 pr 修复此问题：[tomasklaen/uosc#1102](https://github.com/tomasklaen/uosc/pull/1102)

合并用上了，好用🥳

**Comment by wan0ge** [comment]
> 
> uosc 上游已支持输入框中的光标移动：[tomasklaen/uosc@77cb8bb](https://github.com/tomasklaen/uosc/commit/77cb8bb1a17594991b62940d76c4cf363183ecd8) 该实现目前在中文等 utf-8 多字节字符的使用场景下存在 bug，我已提交相应 pr 修复此问题：[tomasklaen/uosc#1102](https://github.com/tomasklaen/uosc/pull/1102)

问个相关问题，在支持光标移动后现在无论是大佬您的配置包还是使用ziggy-windows.exe的包都无法正确在光标位置使用ctrl+v粘贴文本，这个属于uosc此次特性的相关bug吗（另外我不太懂uosc输入框使用粘贴的这部分的构成，我在使用最新uosc和uosc_danmaku时是无法正常使用ctrl+v的，只能添加ziggy.exe文件使用，这是正常的吗？）

**Comment by dyphire** [comment]
> > uosc 上游已支持输入框中的光标移动：[tomasklaen/uosc@77cb8bb](https://github.com/tomasklaen/uosc/commit/77cb8bb1a17594991b62940d76c4cf363183ecd8) 该实现目前在中文等 utf-8 多字节字符的使用场景下存在 bug，我已提交相应 pr 修复此问题：[tomasklaen/uosc#1102](https://github.com/tomasklaen/uosc/pull/1102)
> 
> 问个相关问题，在支持光标移动后现在无论是大佬您的配置包还是使用ziggy-windows.exe的包都无法正确在光标位置使用ctrl+v粘贴文本，这个属于uosc此次特性的相关bug吗

是的，这个是 uosc 的 bug，我都没发现。在 uosc 上游打开一个 issue 反馈吧，等修复

> （另外我不太懂uosc输入框使用粘贴的这部分的构成，我在使用最新uosc和uosc_danmaku时是无法正常使用ctrl+v的，只能添加ziggy.exe文件使用，这是正常的吗？）

关于这个问题详见 https://github.com/dyphire/mpv-config/discussions/195

**Comment by wan0ge** [comment]
> 
> 是的，这个是 uosc 的 bug，我都没发现。在 uosc 上游打开一个 issue 反馈吧，等修复

我不太懂uosc那边的issue模板，以及不知道从何反馈起，以及英语不太好（）能请大佬帮忙开个issue吗

**Comment by dyphire** [comment]
> > 是的，这个是 uosc 的 bug，我都没发现。在 uosc 上游打开一个 issue 反馈吧，等修复
> 
> 我不太懂uosc那边的issue模板，以及不知道从何反馈起，以及英语不太好（）能请大佬帮忙开个issue吗

可以关注 https://github.com/tomasklaen/uosc/issues/1106

**Comment by wan0ge** [comment]
> 
> > （另外我不太懂uosc输入框使用粘贴的这部分的构成，我在使用最新uosc和uosc_danmaku时是无法正常使用ctrl+v的，只能添加ziggy.exe文件使用，这是正常的吗？）
> 
> 关于这个问题详见 [dyphire/mpv-config#195](https://github.com/dyphire/mpv-config/discussions/195)

感谢佬前面提的issue，那边也是光速修复了hhh 光标移动操作算是彻底实现了；我忏悔之前一直没看uosc文档，结合文档和这个讨论我的理解是 uosc想要使用剪贴板那部分功能就需要自己构建ziggy的二进制文件才能使用，所以我说的直接下载两个插件直接使用无法使用Ctrl+v这个情况是正常的，或者就是学大佬您那样`使用 curl 和 mpv 剪贴板属性及本机命令替代 ziggy 的字幕下载和剪贴板功能`才能使用这个部分功能，不知道我这一通理解对不对hhh
