### ISSUE TITLE
[求助]只有1.0.1版本可以正常使用

### ISSUE THREAD

**Issue by RoasDuck** [Tony15246/uosc_danmaku#41]
mpv版本：v0.39.0-240-gfbf86958
插件位置：mpv同目录portable_config\scripts下
情况：只有1.0.1可以正常使用，可以通过源添加，也可以搜索添加，但是后续版本不是显示添加成功但是什么都没加载就是未找到弹幕文件，1.1.2版本通过链接添加是未找到弹幕文件，搜索则是什么都搜索不到

**Comment by Tony15246** [comment]
你是使用的什么操作系统？

**Comment by RoasDuck** [comment]
> 你是使用的什么操作系统？

我使用的是win11系统，运行日志的话不知道是否是这个
[mpv.log](https://github.com/user-attachments/files/17621201/mpv.log)

**Comment by Tony15246** [comment]
日志是这个，等我看一眼日志哈

**Comment by Tony15246** [comment]
> [   0.013][e][uosc_danmaku] script-opts/uosc_danmaku.conf:2 error converting value 'yes                    #×Ô¶¯Ìî³äÏà¹ØÊÓÆµµ¯Ä»' for key 'auto_load'

你看一眼你的`uosc_danmaku.conf`文件，是不是不小心打了什么奇怪的字或者emoji进去。插件因为配置文件的问题，插件运行不了一点。把非英文字符都删掉试一下。最好再切到英文输入法重新打一下换行。然后再试着运行看看。乱码包括不限于下面这些神奇字符哈哈哈

> µ¯Ä»ÏÔÊ¾·¶Î§
> ????????¦¶
> ×Ô¶¯Ìî³äÏà¹ØÊÓÆµµ¯Ä

**Comment by Tony15246** [comment]
或者你把你的`uosc_danmaku.conf`文件发给我，我帮你改一下以后你用我改过的文件再试试

**Comment by RoasDuck** [comment]
> > [   0.013][e][uosc_danmaku] script-opts/uosc_danmaku.conf:2 error converting value 'yes                    #×Ô¶¯Ìî³äÏà¹ØÊÓÆµµ¯Ä»' for key 'auto_load'
> 
> 你看一眼你的`uosc_danmaku.conf`文件，是不是不小心打了什么奇怪的字或者emoji进去。插件因为配置文件的问题，插件运行不了一点。把非英文字符（比如说没用的注释）都删掉试一下。最好再切到英文输入法重新打一下换行。然后再试着运行看看。乱码包括不限于下面这些神奇字符哈哈哈
> 
> > µ¯Ä»ÏÔÊ¾·¶Î§
> > ????????¦¶
> > ×Ô¶¯Ìî³äÏà¹ØÊÓÆµµ¯Ä

感谢感谢，试了几次发现确实是注释以及空格的问题，习惯性添加注释并且对齐了，去掉空格和注释就可以正常运行了

**Comment by Tony15246** [comment]
没事，不用谢(｡•ㅅ•｡)♡
