### ISSUE TITLE
弹幕位置调整

### ISSUE THREAD

**Issue by LOVEgithub12** [Tony15246/uosc_danmaku#47]
![PixPin_2024-11-09_21-16-53](https://github.com/user-attachments/assets/5d857a82-5d50-4b14-beb4-d45145891c3d)
弹幕可以在最上面的位置显示吗？这样可以看弹幕也不会遮挡视频

**Comment by Tony15246** [comment]
这个做不到，那上面黑的地方看着是空的，是因为那个地方由于视频分辨率和电脑屏幕分辨率不完全匹配，所以不在渲染区域里。无论是ass文件的规定标准，还是mpv对于字幕的渲染方式里字幕的边界都是视频的边界，没法渲染到视频外边。

**Comment by Tony15246** [comment]
#48 重构了的弹幕的渲染逻辑，使用osd覆盖手动渲染弹幕，实现了将弹幕渲染到视频画面外的功能，效果如下

![图片](https://github.com/user-attachments/assets/a1b8a348-4970-44a5-aef1-8be9fd90a1f1)

**Comment by LOVEgithub12** [comment]
> #48 重构了的弹幕的渲染逻辑，使用osd覆盖手动渲染弹幕，实现了将弹幕渲染到视频画面外的功能，效果如下
> 
> ![图片](https://private-user-images.githubusercontent.com/94174703/384697326-a1b8a348-4970-44a5-aef1-8be9fd90a1f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzMzcyMjMsIm5iZiI6MTczMTMzNjkyMywicGF0aCI6Ii85NDE3NDcwMy8zODQ2OTczMjYtYTFiOGEzNDgtNDk3MC00NGE1LWFlZjEtOGJlOWZkOTBhMWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDE0NTUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlNmQyNjVjNDBhMDA1NTA0YjEzOGEzODQyMTBmZDhkNjgzZjMxZWNmNWU3MWY5M2NmMWJiMGVhM2NkOTFmODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Bzrj53VIkEf_WOeuBZmtuMZPBCA120WQF8G3AR7dFP8)

太强了

**Comment by thcehocai** [comment]
> 重构了的弹幕的渲染逻辑
新的渲染逻辑似乎会更不平滑？不知道与mpvnet有没有关系，对比release旧版本新的在原帧率下弹幕会时不时有一种加速跳转到前一个位置的感觉 类似于-----1 ----1 --1 -1少了中间---1这种 就好像它在平移的过程中自身也会时不时抖动 补帧之后顿挫感减轻 但还是有 还有一个比较能看出来的地方是上下两个并行的弹幕它们之间的抖动好像挺明显的
