### ISSUE TITLE
xml弹幕无法加载

### ISSUE THREAD

**Issue by 1296018244** [Tony15246/uosc_danmaku#49]
请问我已经把xml文件和视频文件改成一个名称，autoload_local_danmaku=yes也添加了。为啥还是加载不了xml弹幕。弹幕是腾讯的，输入xml弹幕文件地址是在搜索框里面还是哪呀

**Comment by 1296018244** [comment]
![屏幕截图 2024-11-10 220548](https://github.com/user-attachments/assets/33cfcde6-cc3d-412c-9c84-1ad700240483)
这是服务器连接失败意思吗

**Comment by Tony15246** [comment]
> 这是服务器连接失败意思吗

这应该是命令中有一个非法参数`server`的意思，你这个是执行的什么命令？

**Comment by Tony15246** [comment]
> 输入xml弹幕文件地址是在搜索框里面还是哪呀

是点击`从弹幕源添加弹幕`的图标会出来的搜索框里，就是点击下面这个按钮就会出来

![图片](https://github.com/user-attachments/assets/2affa47a-e9ef-422c-bf1e-8f875945bc7c)

**Comment by 1296018244** [comment]
找到添加弹幕开关了，我添加你示例中的url，https://ani.gamer.com.tw/animeVideo.php?sn=36843，它加载弹幕后显示找不到弹幕文件，而且我用搜索弹幕功能也只能搜到文件名，点进去后也找不到弹幕文件，请问这个地方是哪里出了问题呀

**Comment by 1296018244** [comment]
哦哦，没有问题了。我没注意DanmakuFactory.exe的文件路径，没仔细看，直接把你的示例路径复制进去了，已经没事了。感谢！！！
