### ISSUE TITLE
自动匹配弹幕的疑问

### ISSUE THREAD

**Issue by thcehocai** [Tony15246/uosc_danmaku#53]
当我打开一个视频时，如果自动匹配正常工作，那么我会加载出一些弹幕，但是有时过一会我才能反应过来自动匹配的弹幕和当前视频是不匹配的，所以显示弹幕后能不能在哪里看到当前匹配到的是哪一集的弹幕？然后这个自动匹配的问题，比如当我播放G:\media\anime\败犬女主太多了！ (2024)\Season 1\負けヒロインが多すぎる！ - S01E01 - プロ幼馴染み八奈見杏菜の負けっぷり.mkv这个视频时，打开弹幕搜索栏发现上面的默认写着Season 1，所以这个是根据上一级目录名自动填写的吗？

**Comment by Tony15246** [comment]
> 所以显示弹幕后能不能在哪里看到当前匹配到的是哪一集的弹幕

弹幕加载出来以后会自动显示五秒匹配到的是哪一集的弹幕。如果没注意到漏看了，在mpv的控制台里也能看到之前的消息记录；或者重新开关一次弹幕再显示一次匹配到的是哪一集的弹幕。不过这个功能是最近才更新的，最新的一次release还不包含这个功能，用git克隆最新的代码才有。

**Comment by Tony15246** [comment]
> 所以这个是根据上一级目录名自动填写的吗？

对于本地视频文件来说，基本上是的。是在上一级目录名的基础上，使用正则表达式剔除无用的部分匹配出来的。

**Comment by thcehocai** [comment]
> > 所以这个是根据上一级目录名自动填写的吗？
> 
> 对于本地视频文件来说，基本上是的。是在上一级目录名的基础上，使用正则表达式剔除无用的部分匹配出来的。
希望能添加一个功能能选择使用上两级的目录名，因为使用媒体库整理视频文件的人基本上一级目录都是第几季，再上一级才会是番剧名之类的，就像我上面举的例子一样

**Comment by dyphire** [comment]
本地文件的名称解析采用父目录，因为文件名的命名格式过于复杂化没有好的方法准确获取正确名称
相对而言目录名称命名要规范的多，错误率更低。至于为了适配刮削产生的命名不规范只能自行删除预填充内容手动输入，没什么好方法

不过你给的示例算是刮削常见命名方式了，可以考虑适配下
电影/剧场版的目录结构能给下吗

**Comment by thcehocai** [comment]
G:\media\movie\天気の子 (2019)\天気の子 (2019) - 4K.mkv这样的，不过好像确实，电影一般父目录就是电影名，这样看好像确实不能统一。。。。。。不知道有没有什么方法

**Comment by dyphire** [comment]
尝试 #55 更改后的脚本能不能正确提取番剧名

**Comment by thcehocai** [comment]
稍等 我先把其他的脚本也更新一下

**Comment by thcehocai** [comment]
成功是成功了 但我又发现了另外两个问题：
1 我测试了几集发现最新的代码获取到的弹幕数量比release1.1.2版本获取到的几乎都少了40% （配置里均已经去除了重复弹幕blockmode=REPEAT）
2 最新版这个显示匹配到的是哪一集的弹幕是匹配成功了才会显示吗 不知道为什么有的能显示 有的不会显示 但是两者都有弹幕出现 不会显示的手动搜索弹幕匹配后又会显示了

**Comment by thcehocai** [comment]
第一个问题新旧版本也都使用了加载更多弹幕

**Comment by Tony15246** [comment]
关于问题2，理论上是弹幕是匹配成功且弹幕开关为开的状态下，会显示匹配到的是哪一集。我目前测试暂未遇到弹幕加载成功但不显示匹配到的是哪一集的弹幕这种情况。你有遇到这种情况的话，可以把有这个问题的视频发给我，我测试一下看看是什么环节出的问题。

**Comment by Tony15246** [comment]
关于问题1，两个不同版本代码码获取到的弹幕数量不同，中间是隔了几天；还是说就是同一天或者你开着两个版本一起测试的？

**Comment by thcehocai** [comment]
问题一是我就是刚刚直接替换新旧文件测试的 两者的弹幕接口不应该是一样的吗

**Comment by Tony15246** [comment]
> 问题一是我就是刚刚直接替换新旧文件测试的 两者的弹幕接口不应该是一样的吗

理论上肯定是的。我本地测试一下看看问题能不能复现以及是什么问题导致的

**Comment by thcehocai** [comment]
https://github.com/user-attachments/assets/bcb51a64-7643-42d1-8830-373c627e675d

问题2的视频

**Comment by thcehocai** [comment]
从视频1到2再到1，2加载出弹幕能显示哪一集 1不会显示

**Comment by Tony15246** [comment]
关于问题2，经过测试后实际弹幕量并没有变少。ass文件中内容分为两类，dialogue和comment，而comment不会实际显示出来。旧版本统计弹幕量的时候把comment也统计进去了；而新版的代码在重构渲染方式的同时，只统计了会渲染在屏幕上的弹幕的数量，所以弹幕总量看似变小了，其实能看到的弹幕数量没有变。

**Comment by thcehocai** [comment]
> 只统计了会渲染在屏幕上的弹幕的数量，所以弹幕总量看似变小了，其实能看到的弹幕数量没有变。
也就是说实际上能看到的只有dialogue种类的弹幕，旧版把comment种类也统计进去了所以显示更多，所以说新版实际是比旧版更准确是吗 那这两个种类是有啥区别呢

**Comment by Tony15246** [comment]
> 也就是说实际上能看到的只有dialogue种类的弹幕，旧版把comment种类也统计进去了所以显示更多，所以说新版实际是比旧版更准确是吗

就是这样。

ass文件中comment通常用于给字幕制作人员添加备注、指示，或是存储一些不希望观众看到的文本信息。这类信息可能对字幕调整有帮助，但对观看者不重要。

**Comment by Tony15246** [comment]
关于问题1，那个败犬女主第一集你是不是在旧版代码的时候就给这个视频自动加载过弹幕？应该是由于旧版代码在保存弹幕记忆的时候没有存剧集信息，而重新加载的时候都是从记忆中加载的，导致一直不显示剧集信息。你手动加载一次，强行写入新版代码格式的记忆应该重新打开的时候就能正常显示剧集信息了。你试一下看看呢。

**Comment by thcehocai** [comment]
我看主界面代码有更新 我以为确实是有问题修复了 但我记得我放一个新剧集好像也没有 我再拿一个新剧集试试

**Comment by Tony15246** [comment]
OK，你遇到新剧集没有的情况的话也顺便把原视频贴在这里把，我直接下载下来拿原视频测试看看是什么问题。

**Comment by Tony15246** [comment]
> 我看主界面代码有更新 我以为确实是有问题修复了

没有😂，commit`0cccbf7`就是改了一下显示的内容，没改代码逻辑

**Comment by thcehocai** [comment]
目前来看新剧集可以正常显示 应该没啥问题了 如果我遇到新剧集显示不了的会在这下面继续回复 谢谢大佬们了

**Comment by Tony15246** [comment]
没事儿，不用谢(ゝ∀･)

**Comment by thcehocai** [comment]
有个小建议 测试发现弹幕密度和显示范围也会影响显示的加载弹幕数 可以优化一下文本，把共计加载xx条弹幕 改成已获取xx条弹幕 为你显示xx条弹幕这种 个人感觉这样说明更准确 其他用户使用的时候不会误以为那两个选项会影响到插件获取到的弹幕总量 只是个人建议(ゝ∀･)

**Comment by Tony15246** [comment]
OK,会考虑在后续优化的时候把这一点也加上
