### ISSUE TITLE
uosc菜单的增强

### ISSUE THREAD

**Issue by zhongfly** [Tony15246/uosc_danmaku#59]
目前是一个功能一个菜单，能否考虑用一个控件打开一个复合的菜单，从多个选项里选择：搜索名称、从链接添加、从本地文件添加，再打开相应的菜单。
另外，不知道uosc能否实现的是多选菜单，用来开启关闭/切换来源

**Comment by dyphire** [comment]
多选不清楚，复合菜单是可以实现的
欢迎 pr（

**Comment by Tony15246** [comment]
目前总共最多有三个控件，而弹幕开关控件作为一个开关控件肯定不能藏到复合菜单里面去，开关个弹幕不能搞得那么麻烦。从链接添加、从本地文件添加这两个功能实际上是一个入口。所以现阶段就算做了复合菜单，也只有两个菜单项，意义不大，但重构前端的工作量却很大。

~说了这么多，说白了就是我懒狗，暂时还不想重构前端，等到后面功能确实多了再考虑吧~
