### ISSUE TITLE
mpvnet快捷键绑定后没反应

### ISSUE THREAD

**Issue by tsy-548** [Tony15246/uosc_danmaku#6]
能把快捷键弄到script-opts文件夹下的uosc_danmaku.conf中绑定吗？

**Comment by Tony15246** [comment]
> 能把快捷键弄到script-opts文件夹下的uosc_danmaku.conf中绑定吗？

我没有使用过mpvnet，但按照mpvnet的文档来看mpvnet设置快捷键的位置应该也是input.conf。没生效的话会不会是因为和你配置中原本现有的快捷键冲突了？

总之，我重构了一下快捷键绑定的逻辑，改成了可以在uosc_danmaku.conf中绑定。在a0a46099422f0c3dc7b1d34f125f809850e2de92提交中实现了新逻辑，你可以clone下来尝试一下。如果新逻辑也不能正常绑定快捷键的话，就需要你本地的配置、你所在的操作系统、你的mpvnet运行日志这些信息来debug了。

现在快捷键不需要进行设置，已经进行了默认绑定。默认情况下弹幕搜索功能绑定“Ctrl+d”；弹幕开关功能绑定“j”。可以在uosc_danmaku.conf中自定义快捷键，比如说可以像下面这样更改默认快捷键。

```
open_search_danmaku_menu_key=Ctrl+i
show_danmaku_keyboard_key=i
```

**Comment by Tony15246** [comment]
暂时没有报告其他问题，此issue将关闭

**Comment by Tony15246** [comment]
暂时没有报告其他问题，此issue将关闭
