### ISSUE TITLE
弹幕渲染反馈

### ISSUE THREAD

**Issue by thcehocai** [Tony15246/uosc_danmaku#64]
新的渲染逻辑似乎会更不平滑？不知道与mpvnet有没有关系，对比release旧版本新的在原帧率下弹幕会时不时有一种加速跳转到前一个位置的感觉 类似于-----1 ----1 --1 -1少了中间---1这种 就好像它在平移的过程中自身也会时不时抖动 补帧之后顿挫感减轻 但还是有 还有一个比较能看出来的地方是上下两个并行的弹幕它们之间的抖动好像挺明显的

**Comment by Tony15246** [comment]
或许你可以考虑自行调整弹幕渲染间隔和弹幕滚动速度来适配你的使用场景。

下面这一行就是弹幕渲染间隔的参数，修改这个参数会改变弹幕渲染的刷新频率

https://github.com/Tony15246/uosc_danmaku/blob/45354b4d43b289ba8f520342e06bb32a8f8242b2/render.lua#L6

在`uosc_danmaku.conf`里可以设置`scrolltime`选项，修改弹幕的滚动速度

**Comment by thcehocai** [comment]
调了很久感觉都没有之前那种顺滑 总感觉弹幕一抖一抖的

**Comment by thcehocai** [comment]
可以单独设置弹幕的帧率吗 把帧率设置高点感观应该能更好点 视频保持原帧率或60

**Comment by Tony15246** [comment]
帧率本质就是刷新频率，每多少秒刷新一次，这个参数就相当于在设置帧率了

https://github.com/Tony15246/uosc_danmaku/blob/45354b4d43b289ba8f520342e06bb32a8f8242b2/render.lua#L6

> 调了很久感觉都没有之前那种顺滑 总感觉弹幕一抖一抖的

这个参数调很小也没有用吗？

**Comment by thcehocai** [comment]
调了0.0001和12的速度 还是能感觉到

**Comment by thcehocai** [comment]
> 帧率本质就是刷新频率，每多少秒刷新一次，这个参数就相当于在设置帧率了
但是这个也会受到补帧滤镜的影响 经过补帧后能明显感觉拖影和抖动感减轻了

**Comment by thcehocai** [comment]
不开补帧这弹幕看一会感觉就要头晕了 它不是那种稳定的帧率感觉

**Comment by Tony15246** [comment]
> 不开补帧这弹幕看一会感觉就要头晕了 它不是那种稳定的帧率感觉

代码里就是按照INTERVAL设置的秒数循环刷新的，理论上是完全匀速。这种不稳定帧率究竟是从哪来的我也没有头绪🥲

**Comment by thcehocai** [comment]
mpvlazy里测试也是一样的结果。。。新的渲染方式会一卡一卡的 旧版本没有
大佬你测试有这个问题吗

**Comment by Tony15246** [comment]
我用对比了新旧两种方式的渲染效果，在关闭滤镜的情况下，确实新渲染方式比起旧方式存在不匀速的问题。我因为之前一直开着vf滤镜，没注意到有这回事。

**Comment by thcehocai** [comment]
我这里开了补帧也还是有抖动 虽然比较轻微，但正常看也能注意到 应该是原本的就有抖动 所以补了帧也只能减轻。。。

**Comment by Tony15246** [comment]
找到解决方法了，修改

```
local INTERVAL = 0.01 
```

为

```
local INTERVAL = 1 /24 / 10
```

可以解决抖动问题，让新旧两种方式渲染出来的弹幕完全重合

**Comment by thcehocai** [comment]
修改后好像确实感觉不出了

**Comment by Tony15246** [comment]
考虑到插件用户基本都是用来看动漫，常见动漫资源的帧数基本都是23.976帧，我回头推一个pr，修改一下默认的渲染间隔时间

**Comment by thcehocai** [comment]
这个刷新间隔会影响性能吗

**Comment by Tony15246** [comment]
根据我的测试。在我的10代i5笔记本上，无显卡，linux系统,mpv的vo选项为no。

仅使用mpv播放视频，mpv进程的cpu占用率在15%~20%左右，gpu占用在9%左右。

使用vf路径加渲染弹幕，mpv进程的cpu占用率在20%~30%左右，gpu占用在12%左右。

设置`local INTERVAL = 1 / 24 / 10`，mpv进程的cpu占用率在40%~50%，gpu占用在12%左右。

设置`local INTERVAL = 1 / 24 / 1000`，mpv进程的cpu占用率在100%~120%左右，相当于吃满了cpu一个核；gpu占用在12%左右。

**Comment by Tony15246** [comment]
不过这么看下来，性能开销最小的方式反而是开vf滤镜

**Comment by thcehocai** [comment]
但是开vf滤镜解决不了抖动问题吧 你那里开滤镜也能解决这个问题吗

**Comment by Tony15246** [comment]
不好意思😂，开vf滤镜的数据测错了，实际上开vf滤镜的cpu占用要到40%

**Comment by Tony15246** [comment]
那就还是不如设置local INTERVAL = 1 / 24 / 10了

**Comment by thcehocai** [comment]
能消除抖动的vf滤镜参数是什么？

**Comment by dyphire** [comment]
> 找到解决方法了，修改
> 
> ```
> local INTERVAL = 0.01 
> ```
> 
> 为
> 
> ```
> local INTERVAL = 1 / 24 / 10
> ```
> 
> 可以解决抖动问题，让新旧两种方式渲染出来的弹幕完全重合
> 
> 你试一下看看在你那边有没有用

ASS 字幕的事件的最小时间单位是 10ms，所以我当时将渲染间隔设置为了 0.01，忘记了视频帧率也会影响到 OSD 渲染

**Comment by Tony15246** [comment]
> 能消除抖动的vf滤镜参数是什么？

这是我的vf滤镜参数`vf=lavfi="fps=fps=60:round=down"`，在我的环境下能消除抖动，使得新旧渲染弹幕方式渲染出来的弹幕完全重合

**Comment by thcehocai** [comment]
如果是补帧到60的话1 / 24 / 10是不是要把24改成60

**Comment by Tony15246** [comment]
> 如果是补帧到60的话1 / 24 / 10是不是要把24改成60

理论上应该是

**Comment by zhongfly** [comment]
帧率是可以获取到的属性值，可以写成类似于这样的
```lua
local INTERVAL = 1 / mp.get_property_number('estimated-vf-fps') / 10
```
就可以根据帧率自动改

**Comment by Silvertraces** [comment]
> 根据我的测试。在我的10代i5笔记本上，无显卡，linux系统,mpv的vo选项为no。
> 
> 仅使用mpv播放视频，mpv进程的cpu占用率在15%~20%左右，gpu占用在9%左右。
> 
> 使用vf路径加渲染弹幕，mpv进程的cpu占用率在20%~30%左右，gpu占用在12%左右。
> 
> 设置`local INTERVAL = 1 / 24 / 10`，mpv进程的cpu占用率在40%~50%，gpu占用在12%左右。
> 
> 设置`local INTERVAL = 1 / 24 / 1000`，mpv进程的cpu占用率在100%~120%左右，相当于吃满了cpu一个核；gpu占用在12%左右。
> 
> 仅供参考，硬件方面我不是专业的

请问，该脚本的gpu调用（核显/独显）是跟随**mpv.conf**中的配置么？

**Comment by Silvertraces** [comment]
此外还想问设置fps视频滤镜（vf_fps)配置项是开启60帧渲染弹幕叠加层的意思吗？用game bar覆盖看到是这么多，还是说，这个选项是把播放的视频本身都插帧到60了吗。开启该选项后核显渲染的情况（没有配置mpv.conf），gpu占用会很高；独显（4060laptop）渲染的情况，增加的性能开销并不明显，且似乎`local INTERVAL`项的开销影响也不明显了。目前看来，**设置`local INTERVAL = 1 / 24 / 10`，以及`vf_fps=yes`，加上修改mpv默认软解**的方案，应该是能覆盖目前主流游戏本的通用弹幕优化配置了。
![image](https://github.com/user-attachments/assets/d4cbf48f-683b-4eea-b5c5-60bf359c563a)

**Comment by Tony15246** [comment]
> 请问，该脚本的gpu调用（核显/独显）是跟随**mpv.conf**中的配置么？

没错

**Comment by Tony15246** [comment]
> 此外还想问设置fps视频滤镜（vf_fps)配置项是开启60帧渲染弹幕叠加层的意思吗？用game bar覆盖看到是这么多，还是说，这个选项是把播放的视频本身都插帧到60了吗。

vf_fps选项是把视频本身都插帧到60了
