### ISSUE TITLE
请求增加“下载该弹幕到本地”的开关。

### ISSUE THREAD

**Issue by MiKoto-Railgun** [Tony15246/uosc_danmaku#76]
有时候希望将下载的弹幕保存到本地，希望添加一个命令用以保存本地弹幕

**Comment by Tony15246** [comment]
可以，我实现一个保存弹幕功能

**Comment by Tony15246** [comment]
已实现保存弹幕功能，具体使用和功能可查看[readme文件](https://github.com/Tony15246/uosc_danmaku?tab=readme-ov-file#save_danmaku)

**Comment by MiKoto-Railgun** [comment]
可以保存了，就是想问问我都是退出mpv后才出现xml文件，这正常吗？

**Comment by Tony15246** [comment]
> 可以保存了，就是想问问我都是退出mpv后才出现xml文件，这正常吗？

正常的，代码逻辑就是这样的

**Comment by Tony15246** [comment]
> 可以麻烦看一下吗 `# script-message cycle-commands "script-opts uosc_danmaku-save_danmaku=yes;show-text 自动保存弹幕：开" "script-opts uosc_danmaku-save_danmaku=no;show-text 自动保存弹幕：关" #menu: 弹幕 > 开/关 自动保存xml弹幕` input.conf我这么写没反应，是哪里错了

这个显示的格式有问题也没有换行😂，我有点看不明白写了啥， `# script-message cycle-commands "script-opts uosc_danmaku-save_danmaku=yes;show-text 自动保存弹幕：开" "script-opts uosc_danmaku-save_danmaku=no;show-text 自动保存弹幕：关" #menu: 弹幕 > 开/关 自动保存xml弹幕` 这一个大大的`#`写在开头不就把后面的内容全注释掉了，相当于啥也没写吗？

**Comment by Tony15246** [comment]
我突然反应过来你不会是想要把快捷键绑到`#`上吧？`#`代表的是注释，`#`之后的内容都会失效。你随便换个别的快捷键就行。

**Comment by MiKoto-Railgun** [comment]
> 我突然反应过来你不会是想要把快捷键绑到`#`上吧？`#`代表的是注释，`#`之后的内容都会失效。你随便换个别的键来当快捷键就行。

额，跟#没什么，换成其他键也没用，主要是后面的命令应该错了，我想再切换自动保存弹幕开关的时候给出提示，于是就用了cycle-commands循环执行切换命令，后来我只执行
`script-opts uosc_danmaku-save_danmaku=yes`
发现单独执行这个也没反应，osd不显示，也没有自动保存，大佬你单独执行可以不？

**Comment by Tony15246** [comment]
> `script-opts uosc_danmaku-save_danmaku=yes`

这个肯定执行不起来啊😂，因为这不是一个command。mpv能使用的comment只有官方文档里写的[这些](https://mpv.io/manual/stable/#list-of-input-commands)

想要实现属性设置的话，用这个command就好

```
key set script-opts uosc_danmaku-save_danmaku=yes
```

**Comment by Tony15246** [comment]
我猜`cycle-commands`应该是你用的mpv配置里自定义的script message，官方文档里没提到有这个。假设这个`cycle-commands`脚本消息能够正常运行的话，想实现你要的效果应该是这么写`key script-message cycle-commands "set script-opts uosc_danmaku-save_danmaku=yes;show-text 自动保存弹幕：开" "set script-opts uosc_danmaku-save_danmaku=no;show-text 自动保存弹幕：关"`

**Comment by MiKoto-Railgun** [comment]
哦哦哦，明白了，谢谢

**Comment by Tony15246** [comment]
没事儿，不用谢(　ﾟ∀ﾟ) ﾉ♡
