### ISSUE TITLE
希望标题能显示danmaku-delay弹幕延迟

### ISSUE THREAD

**Issue by MiKoto-Railgun** [Tony15246/uosc_danmaku#77]
我之前是用uosc.conf下的

`top_bar_alt_title=${?media-title:${!chapters==0:章节：(${chapters}):${chapter}}${?chapters==0:章节：无} | 播放列表：${playlist-pos-1}/${playlist-count} ${!sub-visibility==no:| 字幕延迟：${sub-delay}} ${!secondary-sub-visibility==no:| 弹幕延迟：${secondary-sub-delay}} | 播放进度：${playback-time/full}/${duration/full} (${percent-pos}%)}`

也就是用次字幕延迟secondary-sub-delay的方式在标题下面显示弹幕延迟

`top_bar_alt_title=${?media-title:${!chapters==0:章节：(${chapters}):${chapter}}${?chapters==0:章节：无} | 播放列表：${playlist-pos-1}/${playlist-count} ${!sub-visibility==no:| 字幕延迟：${sub-delay}} | 弹幕延迟：${danmaku-delay} | 播放进度：${playback-time/full}/${duration/full} (${percent-pos}%)}`

但是现在用danmaku-delay就不行了，会显示error
这一命令所在代码块显示它不保存弹幕延迟数字，应该创建一个参数保存数据
希望danmaku-delay或其他参数能显示延迟数
最好是弹幕延迟不为零时再显示弹幕延迟

**Comment by Tony15246** [comment]
`top_bar_alt_title=${?media-title:${!chapters==0:章节：(${chapters}):${chapter}}${?chapters==0:章节：无} | 播放列表：${playlist-pos-1}/${playlist-count} ${!sub-visibility==no:| 字幕延迟：${sub-delay}} | 弹幕延迟：${danmaku-delay} | 播放进度：${playback-time/full}/${duration/full} (${percent-pos}%)}`

这个地方能够获取到值的变量应该都是property，但是据我所知在插件的角度好像没有办法给mpv自定义一个property出来。而现有的原生property既然被定义出来了，那占用mpv原生的property拿来存弹幕延迟的数据肯定也不合适。我暂时没有想到一个合理的解决方案。

@dyphire 这个问题大佬您有解决思路吗？

**Comment by Tony15246** [comment]
https://github.com/mpv-player/mpv/issues/10732#issuecomment-1273381337

看来似乎的确无法自定义一个property，只有`script-opts`可以自定义设置。那感觉这个问题没有理论上的解决办法了。

除非强行将其他property抢占过来作为弹幕延迟的表示，但这种方式太粗暴太destructive了

**Comment by Tony15246** [comment]
> 应该创建一个参数保存数据

@MiKoto-Railgun 最新的代码中已添加此参数，名称为`user-data/uosc_danmaku/danmaku-delay`，使用方法和你用`secondary-sub-delay`是一样的

> 最好是弹幕延迟不为零时再显示弹幕延迟

这个自己通过`${!NAME==VALUE:STR}`这个形式的Property Expansion语法就能实现，比如说写成这样

```
${!user-data/uosc_danmaku/danmaku-delay==0:弹幕延迟：${user-data/uosc_danmaku/danmaku-delay}}
```

**Comment by 2650951697** [comment]
具体如何操作呢？

**Comment by 2650951697** [comment]
> > 应该创建一个参数保存数据
> 
> @MiKoto-Railgun 最新的代码中已添加此参数，名称为`user-data/uosc_danmaku/danmaku-delay`，使用方法和你用`secondary-sub-delay`是一样的
> 
> > 最好是弹幕延迟不为零时再显示弹幕延迟
> 
> 这个自己通过`${!NAME==VALUE:STR}`这个形式的Property Expansion语法就能实现，比如说写成这样
> 
> ```
> ${!user-data/uosc_danmaku/danmaku-delay==0:弹幕延迟：${user-data/uosc_danmaku/danmaku-delay}}
> ```
具体如何操作呢？

**Comment by 2650951697** [comment]
> > > 应该创建一个参数保存数据
> > 
> > 
> > @MiKoto-Railgun 最新的代码中已添加此参数，名称为`user-data/uosc_danmaku/danmaku-delay`，使用方法和你用`secondary-sub-delay`是一样的
> > > 最好是弹幕延迟不为零时再显示弹幕延迟
> > 
> > 
> > 这个自己通过`${!NAME==VALUE:STR}`这个形式的Property Expansion语法就能实现，比如说写成这样
> > ```
> > ${!user-data/uosc_danmaku/danmaku-delay==0:弹幕延迟：${user-data/uosc_danmaku/danmaku-delay}}
> > ```
> 
> 具体如何操作呢？

这个我操作好了 按照楼主的操作把位置那栏改了 我是想了半天不知道咋操作原来是按楼主的来

**Comment by 2650951697** [comment]
我是下的人型电脑天使心里的一个资源第二集的弹幕是有延迟的 好几秒的延迟 第一集和第三集就没有 第二集是播放了好几秒才出弹幕

**Comment by MiKoto-Railgun** [comment]
> danmaku

看一下你这段代码是怎么甚至的

**Comment by 2650951697** [comment]
![image](https://github.com/user-attachments/assets/7a386eba-559d-49d5-b40c-ffb88f5db4e0)

**Comment by 2650951697** [comment]
我把冲突键的给删了一部分

**Comment by MiKoto-Railgun** [comment]
直接写成 `ALT+1    script-message danmaku-delay +1` 试试

**Comment by 2650951697** [comment]
> 直接写成 `ALT+1 script-message danmaku-delay +1` 试试，括号没必要

好了好了 感谢 已解决 直接复制粘贴有点榆木脑袋了

**Comment by 2650951697** [comment]
还有一个问题好像是自动播放下一集了显示弹幕延迟和上一集一样但是实际是归零的 需要重新设置

**Comment by Tony15246** [comment]
> 还有一个问题好像是自动播放下一集了显示弹幕延迟和上一集一样但是实际是归零的 需要重新设置

是个小问题，`user-data/uosc_danmaku/danmaku-delay`属性的值是在设置之后才会刷新的，没有考虑到自动播放下一集的使用场景。后续会修复这个问题。

**Comment by 2650951697** [comment]
> > 还有一个问题好像是自动播放下一集了显示弹幕延迟和上一集一样但是实际是归零的 需要重新设置
> 
> 是个小问题，`user-data/uosc_danmaku/danmaku-delay`属性的值是在设置之后才会刷新的，没有考虑到自动播放下一集的使用场景。后续会修复这个问题。

okok 这个问题还好 就是我纯小白不知道怎么看当前着色器面板有哪些啊 就是当前配置了哪些 那个是osd还是什么吗 快捷键是哪一个啊

**Comment by Tony15246** [comment]
btw，只是user-data/uosc_danmaku/danmaku-delay的值显示有问题，没有及时更新。弹幕延迟延迟归零，需要重新设置是正常逻辑。

**Comment by 2650951697** [comment]
> btw，只是user-data/uosc_danmaku/danmaku-delay的值显示有问题，没有及时更新。弹幕延迟延迟归零，需要重新设置是正常逻辑。

我看弹幕开关设置能延续我还以为这个也是能延续的呢

**Comment by 2650951697** [comment]
> > > 还有一个问题好像是自动播放下一集了显示弹幕延迟和上一集一样但是实际是归零的 需要重新设置
> > 
> > 
> > 是个小问题，`user-data/uosc_danmaku/danmaku-delay`属性的值是在设置之后才会刷新的，没有考虑到自动播放下一集的使用场景。后续会修复这个问题。
> 
> okok 这个问题还好 就是我纯小白不知道怎么看当前着色器面板有哪些啊 就是当前配置了哪些 那个是osd还是什么吗 快捷键是哪一个啊

这个找到了 不用了

**Comment by Tony15246** [comment]
> okok 这个问题还好 就是我纯小白不知道怎么看当前着色器面板有哪些啊 就是当前配置了哪些 那个是osd还是什么吗 快捷键是哪一个啊

我暂时没看懂你的问题是什么意思😂

我现在实在是困得不行了，得先睡了，还有别的问题我明天再帮你看看

**Comment by 2650951697** [comment]
> > okok 这个问题还好 就是我纯小白不知道怎么看当前着色器面板有哪些啊 就是当前配置了哪些 那个是osd还是什么吗 快捷键是哪一个啊
> 
> 我暂时没看懂你的问题是什么意思😂
> 
> 我现在实在是困得不行了，得先睡了，还有别的问题我明天再帮你看看

好的 大佬晚安
