### ISSUE TITLE
设置了save_danmaku=yes之后没有作用

### ISSUE THREAD

**Issue by gerryzheng1** [Tony15246/uosc_danmaku#83]
我在uosc_danmaku.conf里添加了save_danmaku=yes代码但是不起作用，文件关闭后并没有保存加载的弹幕文件，但是其他添加的代码就可以正常使用

**Comment by Tony15246** [comment]
你使用的是最新版的源代码吗？如果是release v1.2.0的话`save_danmaku`选项还没有加入。

如果你是直接下载或者克隆的最新版源代码，然后出现此问题的话，就把mpv运行日志发给我看一下吧，我帮你找找是什么问题。

**Comment by gerryzheng1** [comment]
[Uploading mpv.log…]()
确实是用的1.2.0不起作用
运行日志是这个吗

**Comment by gerryzheng1** [comment]
ok了 直接下载了最新源代码就可以了

**Comment by gerryzheng1** [comment]
感谢

**Comment by Tony15246** [comment]
不用谢ξ( ✿＞◡❛)
