### ISSUE TITLE
一点信息提示小建议

### ISSUE THREAD

**Issue by MiKoto-Railgun** [Tony15246/uosc_danmaku#90]
大佬要是觉得行的话可不可以改一下提示语的位置

就比如打开视频时显示的“弹幕加载中”会与@dyphire的history-bookmark.lua中的“是否恢复当前目录的上次播放文件”提示语冲突
表现为两个提示语在打开3s时间里互相抢夺显示造成一闪一闪的问题
因为都使用了自带的osd_message方法冲突

还有就是无边框模式下，本插件的提示语显示位置靠上，会被标题栏遮挡

我觉得可行的方法就是新建一个或沿用弹幕的overlay，并允许在options设置新的参数自定义距边框大小
这样无论是其他任何插件都不会冲突了，而且还解决了标题栏遮挡的问题

大佬要是觉得有必要的话，希望可以加这个功能

PS：问句题外话，最多可以新建多少overlay，这对性能会有怎样的影响？

**Comment by Tony15246** [comment]
我会尝试添加一下这个功能，我准备通过复用弹幕的overlay渲染message。

> PS：问句题外话，最多可以新建多少overlay，这对性能会有怎样的影响？

最多可以新建64个。目前暂不清楚多性能影响有多大。但是通过mpv官方文档中的这句话`Note that it's better to put multiple lines into data, instead of adding multiple OSD overlays.`可知mpv官方建议在可能的情况下尽量复用现有的overlay。可以猜测渲染复数个overlay会导致一定的性能问题。

**Comment by Tony15246** [comment]
功能已合并到主分支最新源码。message已重构为由overlay渲染。

在options设置`message_x`和`message_y`两个参数可以自定义距边框大小。

**Comment by MiKoto-Railgun** [comment]
> 功能已合并到主分支最新源码。message已重构为由overlay渲染。
> 
> 在options设置`message_x`和`message_y`两个参数可以自定义距边框大小。

好家伙，这么快，厉害了大佬
