### ISSUE TITLE
为bilibili网站电影添加弹幕支持

### ISSUE THREAD

**Issue by Asina-Edelfelt** [Tony15246/uosc_danmaku#94]
如题，希望对支持添加哔哩哔哩电影弹幕
如：`https://www.bilibili.com/bangumi/play/ss43624?theme=movie`
这个现在就不支持，这个是弹弹play本身就不支持
但可以通过取出网址/ss后的season_id值43624，使用B站自身api
`https://api.bilibili.com/pgc/web/season/section?season_id=43624`
获取json数据并取出cid值或aid值
这样就可以使用弹弹play用cid请求B站电影的弹幕了
希望可以支持

**Comment by MiKoto-Railgun** [comment]
有cid的话都可以用B站自身api请求弹幕了

`https://api.bilibili.com/x/v1/dm/list.so?oid={cid}`

其实现在也支持使用B站电影弹幕
去网页端电影播放页，简介下不是有bv号嘛，复制这一bv链接
手动添加弹幕就行了

不过这样也麻烦，要是大佬可以支持电影网页链接的话就更方便了

**Comment by Tony15246** [comment]
综上所述，你所描述的`https://www.bilibili.com/bangumi/play/ss43624?theme=movie`这种格式的链接，不是电影的网页链接，从逻辑上来讲不应该支持。而真正的电影网页链接的弹幕是支持解析和获取的。

**Comment by Asina-Edelfelt** [comment]
> 综上所述，你所描述的`https://www.bilibili.com/bangumi/play/ss43624?theme=movie`这种格式的链接，不是你所播放的电影episode的网页链接，从逻辑上来讲不应该支持。而真正的电影网页链接的弹幕是支持解析和获取的。

好的，明白了大佬，感谢解惑
